server:
  port: 9999
shiro:
  loginUrl: /login
  unauthorizedUrl: /unauthorized
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algorithm?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: liangbing39024&
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ruyuan.repository.bean
  configuration:
    map-underscore-to-camel-case: true